openapi: 3.0.0
info:
  title: Your API Title
  version: 1.0.0
  description: Description of your API

servers:
  - url: "http://localhost:4002"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Place your JWT token here"

paths:
  /auth/register:
    post:
      summary: Register a new user
      tags:
        - "User"
      description: Register a new user with a username, email, and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: User's username
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  minLength: 5
                  maxLength: 30
                  description: User's password
                roles:
                  type: array
                  items:
                    type: string
                    enum:
                      - CREATOR
                      - VIEWER
                      - VIEW_ALL
                  description: User roles (optional, defaults to ['CREATOR'])
      responses:
        "201":
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
                  error:
                    type: string
                    description: Error details
